name: Build and Test contracts
on: [pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/setup-node@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: yarn install --no-lockfile 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ### Run tests
      - name: Test contracts
        run: npx hardhat test
        env:
          REPORT_GAS: false
          SBT_ROLE_NAME: ${{vars.SBT_ROLE_NAME}}